# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 05:09
from __future__ import unicode_literals

import apps.subscribe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default=apps.subscribe.models._make_uuid, max_length=100, unique=True, verbose_name='Reference')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'subscribe',
                'verbose_name_plural': 'subscribes',
                'ordering': ('email',),
            },
        ),
    ]
