# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_status'),
        ('promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('link_url', oscar.models.fields.ExtendedURLField(blank=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=255, verbose_name='Link text')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('num_products', models.PositiveSmallIntegerField(default=4, verbose_name='Number of Products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category product list',
                'verbose_name_plural': 'Category product lists',
            },
        ),
    ]
