# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20171123_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='full_address',
            field=models.TextField(blank=True, verbose_name='Full address'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='sub_districts',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub-districts'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='line4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fourth line of address'),
        ),
    ]
