# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20171205_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Old Price'),
        ),
    ]
