# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 08:08
from __future__ import unicode_literals

import apps.career.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0005_auto_20171205_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default=apps.career.models._make_uuid, max_length=100, unique=True, verbose_name='Reference')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
                ('document', models.FileField(upload_to='document/career/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Document')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100, unique=True, verbose_name='Departement')),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['departement'],
            },
        ),
        migrations.AddField(
            model_name='career',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Departement', verbose_name='Departement'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.Career', verbose_name='Career'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
    ]
