# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('url', models.CharField(max_length=4000, verbose_name='Url')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('order_number', models.IntegerField(default=1, verbose_name='Position Number')),
            ],
        ),
    ]
