# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170609_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('banned', 'Banned')], default='draft', max_length=50, verbose_name='Status'),
        ),
    ]
