# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True, verbose_name='Category')),
                ('slug', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='PostEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='blog/media/', verbose_name='Image')),
                ('post_body', models.TextField(blank=True, verbose_name='Body')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='postentry',
            name='tags',
            field=models.ManyToManyField(to='blog.PostTag'),
        ),
    ]
