# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=128, unique=True, verbose_name='Order Number')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transfer Date')),
                ('destination_bank', models.CharField(max_length=250, verbose_name='Destination Bank')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('account_owner_name', models.CharField(max_length=250, verbose_name='Account Owner Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(max_length=250, verbose_name='Customer Phone')),
                ('note', models.TextField(verbose_name='Note')),
                ('proof_payment', models.ImageField(max_length=255, null=True, upload_to='images/confirmations/', verbose_name='Proof Of Payment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Confirmation Payment',
                'ordering': ('-date_created',),
            },
        ),
    ]
