# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accept', 'Accept')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='confirmationpayment',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='In case we need to call you about your order', max_length=250, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='confirmationpayment',
            name='order_number',
            field=models.CharField(max_length=128, verbose_name='Order Number'),
        ),
    ]
